server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-eureka-hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.zhifei.cloud.feign.PaymentFeignClient: debug