server:
  port: 8002    #与8001分片只有端口不一样，供集群使用
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  zipkin:
    # zipkin server地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 介于0到1之间，1-全部采样
      probability: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhifei.cloud.entity

eureka:
  client:
    register-with-eureka: true  #是否注册到eureka服务端
    fetch-registry: true  #配合ribbon集群的时候需要设置为true，单节点不影响使用
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true   #访问路径可以显示ip
    instance-id: ${spring.application.name}:${server.port}  #配置显示的是这个微服务实例id，而不是显示自己的主机名

#    需要关闭自我保护模式
#    lease-renewal-interval-in-seconds: 1    #每隔1s发送一个心跳包，默认30s
#    lease-expiration-duration-in-seconds: 2   #eureka service 距离上一次收到这个实例的心跳包隔2s则把这个实例移除，默认90s