server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-openfeign
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

ribbon:
  ConnectTimeout: 5000  #配置feign客户端连接超时时间5s
  ReadTimeout: 5000     #配置feign客户端允许生产者处理的最大时长5s（默认1s）

logging:
  level:
    com.zhifei.cloud.openfeign.PaymentControllerOpenFeign: debug
